import { getDb } from "./db";
import { ObjectId } from "mongodb";

export const SEED_PRODUCTS = [
    {
        name: "ProGuard Safety Helmet Type 1",
        slug: "proguard-safety-helmet-type-1",
        categorySlug: "ppe",
        subcategorySlug: "head-protection",
        description: "High-density polyethylene (HDPE) helmet providing excellent impact protection. Features a 6-point suspension system and adjustable headband for maximum comfort. Vented design for high-temperature work environments.",
        price: "$24.99",
        sku: "PG-SH-100",
        availability: "In Stock",
        brandName: "ProGuard Safety",
        certifications: ["ANSI Z89.1", "CE EN 397"],
        applications: ["Construction", "Manufacturing", "Oil & Gas"],
        images: ["/products/proguard-safety-helmet-type-1.jpg"],
    },
    {
        name: "UltraVision Anti-Fog Safety Goggles",
        slug: "ultravision-anti-fog-safety-goggles",
        categorySlug: "ppe",
        subcategorySlug: "eye-protection",
        description: "Premium safety goggles with dual-pane polycarbonate lens. Advanced anti-fog coating ensures clear vision in humid conditions. Soft PVC frame provides a comfortable seal against dust and chemical splashes.",
        price: "$18.50",
        sku: "UV-AG-200",
        availability: "In Stock",
        brandName: "VisionTech",
        certifications: ["ANSI Z87.1+", "EN 166"],
        applications: ["Chemical Handling", "Laboratory", "Woodworking"],
        images: ["/products/ultravision-anti-fog-safety-goggles.jpg"],
    },
    {
        name: "SoundShield Earmuffs 30dB NRR",
        slug: "soundshield-earmuffs-30db-nrr",
        categorySlug: "ppe",
        subcategorySlug: "hearing-protection",
        description: "Premium over-the-head earmuffs offering 30dB Noise Reduction Rating. Padded headband and ultra-soft foam ear cushions provide all-day comfort. Foldable design for easy storage.",
        price: "$28.00",
        sku: "SS-EM-300",
        availability: "In Stock",
        brandName: "SoundShield",
        certifications: ["ANSI S3.19", "CE EN 352-1"],
        applications: ["Manufacturing", "Aviation", "Landscaping"],
        images: ["/products/soundshield-earmuffs-30db-nrr.jpg"],
    },
    {
        name: "AeroBreath N95 Particulate Respirator",
        slug: "aerobreath-n95-respirator",
        categorySlug: "ppe",
        subcategorySlug: "respiratory-protection",
        description: "NIOSH-approved N95 mask with cool-flow exhalation valve. Designed for hot, dusty work settings. Adjustable nose clip and braided headbands ensure a secure, custom fit.",
        price: "$2.50",
        sku: "AB-N95-500",
        availability: "Out of Stock",
        brandName: "AeroBreath",
        certifications: ["NIOSH N95", "FDA Cleared"],
        applications: ["Healthcare", "Grinding", "Sanding", "Sweeping"],
        images: ["https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=600&auto=format&fit=crop"],
    },
    {
        name: "TitanGrip Cut-Resistant Kevlar Gloves",
        slug: "titangrip-cut-resistant-kevlar-gloves",
        categorySlug: "ppe",
        subcategorySlug: "hand-protection",
        description: "Level 5 cut-resistant gloves made from reinforced Kevlar and stainless steel core. Nitrile micro-foam palm coating provides excellent grip in oily or wet conditions.",
        price: "$14.75",
        sku: "TG-CRG-305",
        availability: "In Stock",
        brandName: "TitanGrip",
        certifications: ["ANSI Cut Level A5", "EN 388:2016"],
        applications: ["Metal Fabrication", "Glass Handling", "Automotive"],
        images: ["/products/titangrip-cut-resistant-kevlar-gloves.webp"],
    },
    {
        name: "Lumina Reflective Safety Vest Class 2",
        slug: "lumina-reflective-safety-vest-class-2",
        categorySlug: "safety-clothing-footwear",
        subcategorySlug: "high-visibility-clothing",
        description: "High-visibility mesh safety vest with 2-inch silver reflective tape. Lightweight and breathable fabric. Features front zipper closure and multiple utility pockets.",
        price: "$12.00",
        sku: "LM-SV-C2",
        availability: "In Stock",
        brandName: "Lumina Wear",
        certifications: ["ANSI/ISEA 107-2015 Class 2"],
        applications: ["Road Work", "Surveying", "Warehousing", "Emergency Response"],
        images: ["/products/lumina-reflective-safety-vest-class-2.png"],
    },
    {
        name: "SecureTread Steel Toe Work Boots",
        slug: "securetread-steel-toe-work-boots",
        categorySlug: "safety-clothing-footwear",
        subcategorySlug: "safety-shoes",
        description: "Heavy-duty leather work boots with composite steel toe protection. Slip-resistant rubber outsole prevents falls on slick surfaces. Electrical hazard (EH) rated.",
        price: "$89.99",
        sku: "ST-WB-901",
        availability: "In Stock",
        brandName: "SecureTread",
        certifications: ["ASTM F2413-18", "Slip Resistance Certified"],
        applications: ["Construction", "Mining", "Heavy Equipment Operation"],
        images: ["/products/securetread-steel-toe-work-boots.png"],
    },
    {
        name: "Guardian Fall Protection Harness Kit",
        slug: "guardian-fall-protection-harness-kit",
        categorySlug: "fall-protection",
        subcategorySlug: "safety-harnesses",
        description: "Complete fall protection kit including a full-body harness with pass-through buckles, 6-foot shock-absorbing lanyard, and a durable carrying bag. High-strength webbing supports up to 310 lbs.",
        price: "$145.00",
        sku: "GF-HK-700",
        availability: "In Stock",
        brandName: "Guardian Fall",
        certifications: ["OSHA 1910.140", "ANSI Z359.11"],
        applications: ["Roofing", "Scaffolding", "Tower Climbing"],
        images: ["/products/guardian-fall-protection-harness-kit.jpg"],
    },
    {
        name: "ABC Dry Chemical Fire Extinguisher 5kg",
        slug: "abc-dry-chemical-fire-extinguisher-5kg",
        categorySlug: "fire-chemical-safety",
        subcategorySlug: "fire-extinguishers",
        description: "Multi-purpose dry chemical fire extinguisher suitable for Class A, B, and C fires. Comes with a wall mounting bracket and easy-to-read pressure gauge.",
        price: "$45.00",
        sku: "FE-ABC-5KG",
        availability: "In Stock",
        brandName: "SafeFire",
        certifications: ["ISI Marked", "CE Certified"],
        applications: ["Offices", "Warehouses", "Vehicles", "Industrial Plants"],
        images: ["/products/abc-dry-chemical-fire-extinguisher-5kg.jpg"],
    },
    {
        name: "High-Visibility Traffic Cone 750mm",
        slug: "high-visibility-traffic-cone-750mm",
        categorySlug: "workplace-safety-signage-barriers",
        subcategorySlug: "traffic-cones",
        description: "Durable PVC traffic cone with fluorescent orange color and high-intensity reflective sleeve for night visibility. Heavy square base for stability.",
        price: "$15.00",
        sku: "TC-750-OR",
        availability: "In Stock",
        brandName: "RoadSafe",
        certifications: ["MUTCD Compliant"],
        applications: ["Road Works", "Traffic Management", "Parking Lots"],
        images: ["/products/high-visibility-traffic-cone-750mm.jpg"],
    },
    {
        name: "Standard Lockout Tagout Kit",
        slug: "standard-lockout-tagout-kit",
        categorySlug: "lockout-tagout",
        subcategorySlug: "lockout-kits",
        description: "Comprehensive LOTO kit containing padlocks, hasps, breaker lockouts, valve lockouts, and danger tags in a durable carrying case.",
        price: "$85.00",
        sku: "LOTO-KIT-STD",
        availability: "In Stock",
        brandName: "SafeLock",
        certifications: ["OSHA 1910.147 Compliant"],
        applications: ["Maintenance", "Electrical Work", "Machinery Servicing"],
        images: ["/products/standard-lockout-tagout-kit.jpg"],
    },
    {
        name: "Industrial First Aid Kit - 50 Person",
        slug: "industrial-first-aid-kit-50-person",
        categorySlug: "emergency-response-first-aid",
        subcategorySlug: "first-aid-kits",
        description: "Wall-mountable metal cabinet containing comprehensive first aid supplies for up to 50 people. Meet ANSI standards for workplace safety.",
        price: "$55.00",
        sku: "FAK-IND-50",
        availability: "In Stock",
        brandName: "MediSafe",
        certifications: ["ANSI/ISEA Z308.1-2015"],
        applications: ["Offices", "Manufacturing Floors", "Construction Sites"],
        images: ["/products/industrial-first-aid-kit-50-person.jpg"],
    },
    {
        name: "Shock Absorbing Lanyard 6ft",
        slug: "shock-absorbing-lanyard-6ft",
        categorySlug: "fall-protection",
        subcategorySlug: "lanyards",
        description: "Heavy-duty 6-foot shock absorbing lanyard with double snap hooks. Designed to reduce fall arrest forces.",
        price: "$45.00",
        sku: "SA-LAN-6FT",
        availability: "In Stock",
        brandName: "Guardian Fall",
        certifications: ["OSHA 1910.140", "ANSI Z359.13"],
        applications: ["Construction", "Tower Climbing"],
        images: ["/products/shock-absorbing-lanyard-6ft.png"],
    },
    {
        name: "Emergency Fire Blanket 1.2m x 1.8m",
        slug: "emergency-fire-blanket-1-2m",
        categorySlug: "fire-chemical-safety",
        subcategorySlug: "fire-blankets",
        description: "Woven fiberglass fire blanket suitable for smothering small fires in kitchens, labs, or workshops.",
        price: "$22.50",
        sku: "FB-1218",
        availability: "In Stock",
        brandName: "SafeFire",
        certifications: ["EN 1869"],
        applications: ["Kitchens", "Laboratories", "Workshops"],
        images: ["/products/emergency-fire-blanket-1-2m.jpg"],
    },
    {
        name: "Portable Folding Aluminum Stretcher",
        slug: "portable-folding-aluminum-stretcher",
        categorySlug: "emergency-response-first-aid",
        subcategorySlug: "stretchers",
        description: "Lightweight, high-strength folding stretcher for emergency patient transport.",
        price: "$120.00",
        sku: "FAS-200",
        availability: "In Stock",
        brandName: "MediSafe",
        certifications: ["CE Certified"],
        applications: ["Emergency Services", "Industrial Clinics"],
        images: ["/products/portable-folding-aluminum-stretcher.jpg"],
    },
    {
        name: "Caution Wet Floor Warning Board",
        slug: "caution-wet-floor-warning-board",
        categorySlug: "workplace-safety-signage-barriers",
        subcategorySlug: "warning-boards",
        description: "Bright yellow A-frame warning board. Highly visible with bilingual text.",
        price: "$12.00",
        sku: "WB-WF-01",
        availability: "In Stock",
        brandName: "RoadSafe",
        certifications: ["OSHA Compliant"],
        applications: ["Facilities Management", "Janitorial"],
        images: ["/products/caution-wet-floor-warning-board.jpg"],
    },
    {
        name: "Non-Conductive Safety Padlock Red",
        slug: "non-conductive-safety-padlock-red",
        categorySlug: "lockout-tagout",
        subcategorySlug: "safety-padlocks",
        description: "Nylon body lockout padlock with insulated shackle. Key retaining feature ensures padlock is not left unlocked.",
        price: "$9.50",
        sku: "LOTO-PL-RED",
        availability: "In Stock",
        brandName: "SafeLock",
        certifications: ["OSHA 1910.147 Compliant"],
        applications: ["Electrical Maintenance", "Equipment Isolation"],
        images: ["/products/non-conductive-safety-padlock-red.jpg"],
    },
    {
        name: "Multi-Gas Detector (H2S, CO, O2, LEL)",
        slug: "multi-gas-detector-4-gas",
        categorySlug: "gas-detection-confined-space",
        subcategorySlug: "portable-gas-detectors",
        description: "Portable 4-gas monitor providing reliable detection of combustible gases, oxygen, hydrogen sulfide, and carbon monoxide.",
        price: "$450.00",
        sku: "MGD-4X",
        availability: "In Stock",
        brandName: "GasAlert",
        certifications: ["ATEX", "UL Certified"],
        applications: ["Confined Space Entry", "Oil & Gas", "Sewer Work"],
        images: ["/products/multi-gas-detector-4-gas.jpg"],
    },
    {
        name: "Confined Space Ventilation Blower",
        slug: "confined-space-ventilation-blower",
        categorySlug: "gas-detection-confined-space",
        subcategorySlug: "ventilation-systems",
        description: "High-output axial fan for positive or negative pressure ventilation in confined spaces.",
        price: "$320.00",
        sku: "CS-VB-8IN",
        availability: "Made to Order",
        brandName: "AirFlow Pro",
        certifications: ["CE Certified"],
        applications: ["Manhole Entry", "Tank Cleaning"],
        images: ["/products/confined-space-ventilation-blower.jpg"],
    },
    {
        name: "1000V Insulated Screwdriver Set",
        slug: "1000v-insulated-screwdriver-set",
        categorySlug: "electrical-safety-equipment",
        subcategorySlug: "insulated-tools",
        description: "7-piece VDE rated insulated screwdriver set for electrical work up to 1000V AC.",
        price: "$55.00",
        sku: "IS-SET-7",
        availability: "In Stock",
        brandName: "VoltSafe",
        certifications: ["VDE", "IEC 60900"],
        applications: ["Electrical Installation", "Panel Wiring"],
        images: ["/products/1000v-insulated-screwdriver-set.jpg"],
    },
    {
        name: "40 Cal/cm2 Arc Flash Suit",
        slug: "40-cal-arc-flash-suit",
        categorySlug: "electrical-safety-equipment",
        subcategorySlug: "arc-flash-gear",
        description: "Comprehensive arc flash protection kit including hood, coat, and bib overalls rated for 40 cal/cm2.",
        price: "$850.00",
        sku: "AFS-40CAL",
        availability: "Made to Order",
        brandName: "VoltSafe",
        certifications: ["NFPA 70E", "ASTM F1506"],
        applications: ["High Voltage Switching", "Electrical Substation"],
        images: ["/products/40-cal-arc-flash-suit.jpg"],
    }
];

export async function seedProducts() {
    const db = await getDb();
    const productsColl = db.collection("products");

    // Clear existing products to avoid duplicates during seed
    await productsColl.deleteMany({});

    for (const p of SEED_PRODUCTS) {
        const doc: any = { ...p };
        doc._id = new ObjectId();
        await productsColl.insertOne(doc);
    }
    return { ok: true, count: SEED_PRODUCTS.length };
}
